// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: huzzzmlouawsdtbzczum

class SupabaseConfig {
  static const String supabaseUrl = 'https://huzzzmlouawsdtbzczum.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1enp6bWxvdWF3c2R0YnpjenVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NDI3NTcsImV4cCI6MjA4MDMxODc1N30.FtrnWXDGNPlubbexpiuZ59adL5Ee_KjJNouwk961t10';
}
